In [ ]:
# WEEK_0 assignment

In [1]:
# 파이썬 3이 설치되었는지 확인(3.xx -> 파이썬 3 임)
!python --version

Python 3.9.13


## 1. 자료형

In [2]:
# 다음과 같은 결과가 나오도록 괄호 안의 값을 채우세요.

type(  1  )

int

In [3]:
type(  1.0  )

float

In [4]:
type(  '하이'  )

str

## 2. 리스트

In [5]:
# 다음과 같은 결과가 나오도록 인덱싱 하세요.

a = [1,2,3,4,5]
print(a[4])

5


In [7]:
print(a[0:2])

[1, 2]


In [9]:
print(a[0:4])

[1, 2, 3, 4]


## 3. 딕셔너리(dictionary)

In [14]:
# 다음과 같은 결과가 나오도록 print 문을 완성하세요.
me = {'height': 180}
print(me['height'])

180


In [15]:
# 다음과 같은 결과가 나오도록 코드를 완성하세요.
me = {'height': 180, 'wight': 70}
# 여기에 코드를 입력하세요
print(me)

{'height': 180, 'wight': 70}


## 4. if 문

In [16]:
# 다음과 같은 결과가 나오도록 코드를 완성하세요.

hungry = 'hungry'

if hungry:
    print('im hungry')
    
else:
    print('im not hungry')

im hungry


## 5. for 문

In [26]:
# 다음과 같은 결과가 나오도록 코드를 완성하세요.

list = range(1,7,1)

for i in list:
    print(i)

1
2
3
4
5
6


## 6. 함수

In [19]:
# 다음과 같은 결과가 나오도록 함수를 완성하세요

def hello(object):
    print('hello world', object)
    
hello('관형')

hello world 관형


## 7. 클래스

In [60]:
# 다음과 같은 결과가 나오도록 클래스를 완성하세요

class Man:
    def __init__(self, name):
        self.name=name
    def hello(self):
        print('initialized!')
        print('hello',self.name,'!')
    def goodbye(self):
        print('good-bye', self.name,'!')
        
m = Man('david')
m.hello()
m.goodbye()

initialized!
hello david !
good-bye david !


## 8. 넘파이

In [23]:
import numpy as np

In [32]:
# 다음과 같은 결과가 나오도록 x 를 완성하세요

x = np.arange(3.0)

print(x)
type(x)

[0. 1. 2.]


numpy.ndarray

In [36]:
# 다음과 같은 결과가 나오도록 print 문을 완성하세요(힌트: 사칙연산)

x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

print(  3*x )
print( -1*x  )
print(  x*y )
print( x/y  )

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [38]:
# 다음과 같은 결과가 나오도록 A를 완성하세요

A = np.array([
    [1, 2],
    [3, 4]
])

print(A)
print()
print(A.shape)
print()
print(A.dtype)

[[1 2]
 [3 4]]

(2, 2)

int32


In [39]:
# 다음과 같은 결과가 나오도록 B를 완성하세요

B = np.array([
    [3, 0],
    [0, 6]
])
print(A+B)
print()
print(A*B)

[[ 4  2]
 [ 3 10]]

[[ 3  0]
 [ 0 24]]


In [44]:
# 다음과 같은 결과가 나오도록 print문을 완성하세요

X = np.array([[51, 55],
              [14, 19],
              [0,4]])
print(X)
print()
print( X[0]  )
print( X[0,1]  )

[[51 55]
 [14 19]
 [ 0  4]]

[51 55]
55


In [48]:
# 다음과 같은 결과가 나오도록 X를 사용하여 ~~ 부분을 완성하세요(힌트: flat)

F = X.reshape(-1)
print(F)

[51 55 14 19  0  4]
